from get_mnv import snpeff
import argparse
import textwrap

def main():
    parser = argparse.ArgumentParser(
        description='This program is used to annotate MNV based on genomic data. Select one of the available options to perform different operations.', 
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    subparsers = parser.add_subparsers(
        dest='option', 
        help=textwrap.dedent('''\
            The available options are:
            - "snpeff": SNPEff annotation of MNV.
        ''')
    )
    
    # Parser for "snpff" option
    snpeff_parser = subparsers.add_parser('snpeff', help='Annotate MNVs in a VCF file generated by SNPEff.')
    snpeff_parser.add_argument('-v', '--vcf', required=True, help="VCF file generated by SNPEff.")
    snpeff_parser.add_argument('-f', '--fasta', required=True, help="Reference fasta used in annotation")
    snpeff_parser.add_argument('-g', '--genes', required=True, help="Gene list to annotate.")
    args = parser.parse_args()

    try:
        if args.option == 'train':
            snpeff.get_snpeff(args.vcf, args.fasta, args.genes)
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()