[package]
name = "get_mnv"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "get_mnv"
path = "src/main.rs"

[dependencies]
bio = "0.41.0"
clap = { version = "4.0.32", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
rust-htslib = { version = "0.37.0", default-features = false, features = ["static"] }
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
protein-translate = "0.2.0" 
