// Browser stand-ins for the Tauri runtime, so the real desktop app renders in a
// plain browser with fixture data. `vite.demo.config.ts` aliases every
// `@tauri-apps/*` module the app imports to the matching export below.
//
// Nothing here reimplements analysis. Each command returns a canned answer taken
// from, or shaped like, the output of the real backend on scenario 02a, which is
// enough for every screen to render and for the tutorial screenshots to show the
// actual components rather than mock-ups of them.
import sampleBamView from "./sample_bam_view.json";
import sampleTsv from "./sample_tsv.json";

/**
 * Paths the file pickers hand back, so the form fills in as it would. These are
 * the files in `example/`, and the counts below are what `get_mnv` really
 * reports on them, so every screen in the demo describes one dataset.
 */
export const DEMO_PATHS = {
  vcf: "/data/G35894.var.snp.vcf",
  fasta: "/data/MTB_ancestor.fas",
  annotation: "/data/anot_genes.txt",
  bam: "/data/G35894.demo.bam",
  outputDir: "/data/results",
} as const;

// Copied from the `--summary-json` of:
//   get_mnv --vcf example/G35894.var.snp.vcf --fasta example/MTB_ancestor.fas \
//           --genes example/anot_genes.txt  --bam example/G35894.demo.bam
const RUN_SUMMARY = {
  schema_version: "1.0",
  sample: "G35894",
  dry_run: false,
  bam_provided: true,
  translation_table: 11,
  inputs: {
    vcf: DEMO_PATHS.vcf,
    fasta: DEMO_PATHS.fasta,
    annotation: DEMO_PATHS.annotation,
    bam: DEMO_PATHS.bam,
    checksums: {
      vcf_sha256: "demo-fixture",
      fasta_sha256: "demo-fixture",
      annotation_sha256: "demo-fixture",
      bam_sha256: "demo-fixture",
    },
  },
  output_tsv: "/data/results/G35894.var.snp.MNV.tsv",
  output_vcf: undefined,
  output_bcf: undefined,
  contigs: [
    {
      contig: "MTB_anc",
      snp_records_in_vcf: 950,
      mapped_genes: 635,
      produced_variants: 941,
      snp_variants: 797,
      mnv_variants: 0,
      snp_mnv_variants: 10,
      indel_variants: 0,
      intergenic_variants: 134,
      region_cache_hits: 0,
      region_cache_misses: 635,
    },
  ],
  timings: { parse_inputs_ms: 15, process_ms: 401, emit_ms: 2, total_ms: 434 },
  global: {
    contig_count: 1,
    snp_records_in_vcf: 950,
    mapped_genes: 635,
    produced_variants: 941,
    snp_variants: 797,
    mnv_variants: 0,
    snp_mnv_variants: 10,
    indel_variants: 0,
    intergenic_variants: 134,
    region_cache_hits: 0,
    region_cache_misses: 635,
  },
};

// ── @tauri-apps/api/event ───────────────────────────────────────────────────

type EventCallback = (event: { payload: unknown }) => void;
const listeners = new Map<string, Set<EventCallback>>();

export function listen<T = unknown>(
  name: string,
  handler: (event: { payload: T }) => void,
): Promise<() => void> {
  const set = listeners.get(name) ?? new Set();
  set.add(handler as EventCallback);
  listeners.set(name, set);
  return Promise.resolve(() => set.delete(handler as EventCallback));
}

export function emit(name: string, payload: unknown): void {
  for (const handler of listeners.get(name) ?? []) handler({ payload });
}

// ── @tauri-apps/api/core ────────────────────────────────────────────────────

/** Let a screenshot catch the run mid-flight instead of finishing instantly. */
const RUN_STEPS = [
  { phase: "Parsing inputs", contig: null, current: 0, total: 3 },
  { phase: "Annotating", contig: "MTB_anc", current: 1, total: 3 },
  { phase: "Writing output", contig: null, current: 2, total: 3 },
];

const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export async function invoke<T = unknown>(
  cmd: string,
  args?: Record<string, unknown>,
): Promise<T> {
  switch (cmd) {
    case "get_core_version":
      return "1.1.5 (demo)" as T;

    case "detect_variant_input_format":
      return (String(args?.path ?? "").endsWith(".vcf") ? "vcf" : "tsv") as T;

    case "get_gff_features":
      return ["CDS", "gene", "exon"] as unknown as T;

    case "ensure_fasta_index":
    case "write_text_file":
      return undefined as T;

    case "resolve_output_paths":
      return [RUN_SUMMARY.output_tsv] as unknown as T;

    // Nothing to overwrite in the demo, so the confirmation prompt stays out of
    // the way.
    case "check_output_conflicts":
      return [] as unknown as T;

    case "run_analysis":
      for (const step of RUN_STEPS) {
        emit("analysis-progress", step);
        await wait(450);
      }
      return RUN_SUMMARY as unknown as T;

    case "read_tsv_file":
      return sampleTsv as unknown as T;

    // One real pileup, regenerated by `regenerate_demo_bam_view_fixture` in
    // src-tauri. It is the Rv2036 codon, the only locus the tiny example BAM
    // covers; the demo hands it back for whichever locus is selected, so pick
    // Rv2036 in the locus list to see reads that belong to the row.
    case "get_bam_view":
      return sampleBamView as unknown as T;

    default:
      return Promise.reject(new Error(`demo: unmocked Tauri command '${cmd}'`));
  }
}

// ── @tauri-apps/api/webview ─────────────────────────────────────────────────

/** Drag and drop is a native event the browser cannot raise; accept the
 *  listener and never fire it. The demo fills inputs through the pickers. */
export function getCurrentWebview() {
  return {
    onDragDropEvent(): Promise<() => void> {
      return Promise.resolve(() => {});
    },
  };
}

// ── @tauri-apps/plugin-dialog ───────────────────────────────────────────────

/** The picker cannot open a native dialog, so it answers with the fixture path
 *  that matches what was asked for. Clicking any Browse button fills that field. */
interface DialogFilter {
  name?: string;
  extensions?: string[];
}

interface DialogOptions {
  directory?: boolean;
  multiple?: boolean;
  filters?: DialogFilter[];
}

export function open(options?: DialogOptions): Promise<string | string[] | null> {
  if (options?.directory) return Promise.resolve(DEMO_PATHS.outputDir);
  const names: string[] = (options?.filters ?? []).flatMap(
    (filter) => filter.extensions ?? [],
  );
  const wanted = names.map((n) => n.toLowerCase());
  const pick = wanted.includes("bam")
    ? DEMO_PATHS.bam
    : wanted.some((n) => ["fa", "fasta", "fas", "fna"].includes(n))
      ? DEMO_PATHS.fasta
      : wanted.some((n) => ["gff", "gff3", "gtf"].includes(n))
        ? DEMO_PATHS.annotation
        : DEMO_PATHS.vcf;
  return Promise.resolve(options?.multiple ? [pick] : pick);
}

export function save(options?: DialogOptions): Promise<string | null> {
  const ext = options?.filters?.[0]?.extensions?.[0] ?? "tsv";
  return Promise.resolve(`${DEMO_PATHS.outputDir}/export.${ext}`);
}

export function message(text: string): Promise<void> {
  window.alert(text);
  return Promise.resolve();
}

export function confirm(text: string): Promise<boolean> {
  return Promise.resolve(window.confirm(text));
}

// ── @tauri-apps/plugin-shell ────────────────────────────────────────────────

/** Named `openPath` so it does not collide with the dialog's `open` above;
 *  the shell alias re-exports it under the name the app imports. */
export function openPath(target: string): Promise<void> {
  window.open(target, "_blank", "noopener");
  return Promise.resolve();
}
